"use client";
import {FormEvent,useEffect,useState} from "react";
import {useI18n} from "@/components/I18nProvider";
type User={email:string;first_name:string;last_name:string;company:string|null;account_type:string;country:string;state:string;city:string;address1:string;postcode:string;phone:string};
export default function Profile(){
  const {t}=useI18n();const [user,setUser]=useState<User|null>(null);const [error,setError]=useState("");const [saved,setSaved]=useState(false);
  useEffect(()=>{fetch("/api/account/profile",{cache:"no-store"}).then(async r=>{if(r.status===401){location.href="/login";return null;}const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(d=>d&&setUser(d.user)).catch(e=>setError(e.message));},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaved(false);setError("");const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/account/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error);return;}setSaved(true);}
  if(!user)return <div className="page"><p>{t("common.loading")}</p>{error&&<p className="error">{error}</p>}</div>;
  return <div className="page accountPage"><p className="kicker">{t("account.profileKicker")}</p><h1 className="pageTitle">{t("account.profileTitle")}</h1><p className="pageIntro">{t("account.profileCopy")}</p><form className="form" onSubmit={submit}><div className="formGrid"><label className="field">{t("signup.first")}<input name="firstName" defaultValue={user.first_name} required/></label><label className="field">{t("signup.last")}<input name="lastName" defaultValue={user.last_name} required/></label><label className="field full">{t("common.email")}<input value={user.email} readOnly/></label><label className="field">{t("signup.accountType")}<select name="accountType" defaultValue={user.account_type}><option value="individual">{t("signup.individual")}</option><option value="company">{t("common.company")}</option></select></label><label className="field">{t("common.company")}<input name="company" defaultValue={user.company||""}/></label><label className="field">{t("signup.phone")}<input name="phone" defaultValue={user.phone} required/></label><label className="field">{t("signup.country")}<input name="country" maxLength={2} defaultValue={user.country} required/></label><label className="field">{t("signup.state")}<input name="state" defaultValue={user.state} required/></label><label className="field">{t("common.city")}<input name="city" defaultValue={user.city} required/></label><label className="field full">{t("signup.street")}<input name="address1" defaultValue={user.address1} required/></label><label className="field">{t("signup.postcode")}<input name="postcode" defaultValue={user.postcode} required/></label></div>{saved&&<p className="success">{t("account.saved")}</p>}{error&&<p className="error">{error}</p>}<button className="primary">{t("common.save")}</button></form></div>;
}
